name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: PR Lint
        uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: ${{ secrets.PR_TOKEN }}
          title-regex: '#[eE][xX]-[0-9]+'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          on-failed-regex-comment: 'This is just an example. Failed regex: `%regex%`!'
          on-succeeded-regex-dismiss-review-comment: 'This is just an example. Success!'
